"""Sensors router – crowd density, sustainability metrics, and operational alerts.

Data is generated by the simulator service (``services.simulators``) which
produces realistic-looking telemetry for demonstration purposes.
"""

from __future__ import annotations

import logging

from fastapi import APIRouter

from app.schemas import (
    CrowdDensity,
    OperationalAlert,
    SensorSnapshot,
    SustainabilityMetrics,
    ZoneId,
)
from app.services.simulators import (
    generate_alerts,
    generate_crowd_density,
    generate_sustainability,
)
from app.utils import ttl_cache

logger = logging.getLogger("ssa.sensors")

router = APIRouter()


@router.get(
    "/snapshot",
    response_model=SensorSnapshot,
    summary="Full sensor telemetry snapshot",
)
@ttl_cache(ttl_seconds=5)
def snapshot() -> SensorSnapshot:
    """Return a complete snapshot of all simulated sensor data.

    Includes crowd density per zone, sustainability metrics, and
    any active operational alerts.
    """
    crowd = generate_crowd_density()
    sustainability = generate_sustainability()
    alerts = generate_alerts()

    logger.debug(
        "Sensor snapshot – zones=%d alerts=%d",
        len(crowd),
        len(alerts),
    )

    return SensorSnapshot(
        crowd=crowd,
        sustainability=sustainability,
        alerts=alerts,
    )


@router.get(
    "/crowd",
    response_model=list[CrowdDensity],
    summary="Crowd density per zone",
)
@ttl_cache(ttl_seconds=5)
def crowd() -> list[CrowdDensity]:
    """Return crowd density readings for every stadium zone."""
    return generate_crowd_density()


@router.get(
    "/sustainability",
    response_model=SustainabilityMetrics,
    summary="Real-time sustainability metrics",
)
@ttl_cache(ttl_seconds=5)
def sustainability() -> SustainabilityMetrics:
    """Return energy, water, waste, and carbon offset metrics."""
    return generate_sustainability()


@router.get(
    "/alerts",
    response_model=list[OperationalAlert],
    summary="Active operational alerts",
)
@ttl_cache(ttl_seconds=5)
def alerts() -> list[OperationalAlert]:
    """Return current staff-facing operational alerts."""
    return generate_alerts()


@router.get(
    "/zones",
    response_model=list[dict[str, str]],
    summary="List all stadium zones",
)
@ttl_cache(ttl_seconds=3600)
def zones() -> list[dict[str, str]]:
    """Return metadata for all known stadium zones."""
    return [{"id": z.value, "name": z.name.replace("_", " ").title()} for z in ZoneId]
